CREATE TABLE susep (
        "index" BIGINT,
        "Nome" TEXT,
        "Número de corretor *" FLOAT,
        "CPF/CNPJ" TEXT,
        "Situação" TEXT,
        "Microsseguros" BIGINT,
        "Planos de Capitalização" BIGINT,
        "Seguros de Pessoas" BIGINT,
        "Planos de Previdência Complementar" BIGINT,
        "Seguros de Danos" BIGINT
);
CREATE INDEX ix_susep_index ON susep ("index");
CREATE TABLE empresas_filtradas2(
  "index" INT,
  Nome TEXT,
  "Número de corretor *" REAL,
  "CPF/CNPJ" TEXT,
  "Situação" TEXT,
  Microsseguros INT,
  "Planos de Capitalização" INT,
  "Seguros de Pessoas" INT,
  "Planos de Previdência Complementar" INT,
  "Seguros de Danos" INT,
  CNPJBASICO INT,
  "NOME:1" TEXT,
  "NATUREZA JURIDICA" INT,
  RESPONSAVEL INT,
  CAPITAL TEXT,
  PORTE REAL,
  ENTE TEXT,
  "CNPJBASICO:1" INT,
  CNPJORDEM INT,
  CNPJDV INT,
  MATRIZFILIAL INT,
  "NOME:2" TEXT,
  SITUACAO INT,
  DATASITUACAOCADASTRAL INT,
  MOTIVOSITUACAOCADASTRAL INT,
  NOMEDACIDADENOEXTERIOR TEXT,
  PAIS REAL,
  DATADEINICIOATIVIDADE INT,
  CNAEFISCALPRINCIPAL INT,
  "CNAEFISCALSECUNDÁRIA" TEXT,
  TIPODELOGRADOURO TEXT,
  LOGRADOURO TEXT,
  NUMERO TEXT,
  COMPLEMENTO TEXT,
  BAIRRO TEXT,
  CEP TEXT,
  UF TEXT,
  MUNICIPIO INT,
  DDD1 TEXT,
  TELEFONE1 TEXT,
  DDD2 REAL,
  TELEFONE2 TEXT,
  DDDDOFAX TEXT,
  FAX TEXT,
  CORREIOELETRONICO TEXT,
  SITUACAOESPECIAL TEXT,
  DATADASITUACAOESPECIAL REAL
);
CREATE TABLE IF NOT EXISTS "Cnaes" (
        "CODIGO" BIGINT,
        "DESCRICAO" TEXT
);
CREATE TABLE IF NOT EXISTS "Naturezas" (
        "CODIGO" BIGINT,
        "DESCRICAO" TEXT
);
CREATE TABLE IF NOT EXISTS "Qualificacoes" (
        "CODIGO" BIGINT,
        "DESCRICAO" TEXT
);
CREATE TABLE IF NOT EXISTS "Municipios" (
        "CODIGO" BIGINT,
        "DESCRICAO" TEXT
);
CREATE TABLE IF NOT EXISTS "Paises" (
        "CODIGO" BIGINT,
        "DESCRICAO" TEXT
);
CREATE TABLE IF NOT EXISTS "Motivos" (
        "CODIGO" BIGINT,
        "DESCRICAO" TEXT
);
CREATE TABLE IF NOT EXISTS "Simples" (
        "CNPJBASICO" BIGINT,
        "OPCAOPELOSIMPLES" TEXT,
        "DATADEOPCAOPELOSIMPLES" BIGINT,
        "DATADEEXCLUSAODOSIMPLES" BIGINT,
        "OPCAOPELOMEI" TEXT,
        "DATADEOPCAOPELOMEI" BIGINT,
        "DATADEEXCLUSAODOMEI" BIGINT
);
CREATE TABLE sociosfiltrados(
  CNPJBASICO INT,
  IDENTIFICADORDESOCIO INT,
  NOMEDOSOCIO TEXT,
  CNPJCPFDOSOCIO TEXT,
  QUALIFICACAODOSOCIO INT,
  DATADEENTRADASOCIEDADE INT,
  PAIS REAL,
  REPRESENTANTELEGAL TEXT,
  NOMEDOREPRESENTANTE TEXT,
  QUALIFICACAODOREPRESENTANTELEGAL INT,
  FAIXAETARIA INT
);